config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admin do
    resources :posts
  end

  
  get 'admin', to: 'admin#index'

  post '/tinymce_assets' => 'tinymce_assets#create'
  get 'index', to: 'page#index'
  root 'page#index'
  
  #get '*path', to: 'page#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_secure_token :auth_token
  belongs_to :admin

  mount_uploader :thumbnail, ImageUploader
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  authorize_resource

  def index
    service = FireStore.new(current_admin)
    @posts = service.posts
  end

  def new
    @post = current_admin.posts.new
  end

  def create
    staticImage = StaticImage.create(:image => params[:post][:thumbnail])
    service = FireStore.new(current_admin, 
                            post_params[:title], 
                            post_params[:content],
                            staticImage.image.special.url,
                            Time.now.strftime("%F"))

    service.create_post
    redirect_to admin_posts_path
  end

  def edit
    service = FireStore.new(current_admin)
    post = service.get_post(params[:id]).get
    @post = Post.new(title: post[:title], content: post[:content], :thumbnail => post[:thumbnail])
  end

  def update
    staticImage = StaticImage.create(:image => params[:post][:thumbnail])
    service = FireStore.new(current_admin, 
      post_params[:title], 
      post_params[:content],
      staticImage.image.special.url)
    service.update_post(params[:id])
    redirect_to admin_posts_path
  end

  def destroy
    service = FireStore.new(current_admin)
    post = service.delete_post(params[:id])
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :thumbnail)
  end
end

app/views/admin/posts/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for([:admin,@post], url: action_name == 'new' ? admin_posts_path : admin_post_path, 
                  method: action_name == 'new' ? :post : :patch ) do |f| %>
      <div class="form-group">
        <label>縮圖</label>
        <%= f.file_field :thumbnail, :class => "form-control" %>
      </div>
      <div class="form-group">
        <label>Text Input</label>
        <%= f.text_field :title, class: 'form-control' %>
          <p class="help-block">Example block-level help text here.</p>
      </div>
      <div class="form-group">
        <label>Text area</label>
        <%= f.text_area :content, :class => "form-control ckeditor", :rows => 40, :cols => 120 %>
      </div>
      <button type="submit" class="btn">送出</button>
      <% end %>
  </div>
  <!-- /.col-lg-6 (nested) -->
</div>
<!-- /.row (nested) -->

app/views/admin/posts/edit.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">編輯</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Blog Elements
                </div>
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/posts/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">部落格文章管理</h1>
    </div>
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          文章列表
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Thumbnail</th>
                  <th>Title</th>
                  <th>Content</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @posts.get do |post|  %>
                <tr>
                  <td><%= post.document_id %></td>
                  <td><img src="<%= post[:thumbnail] %>" alt="Thumbnail"></td>
                  <td><%= post[:title] %></td>
                  <td><%= raw post[:content] %></td>
                  <td>
                    <%= link_to "New", new_admin_post_path, class: "btn btn-default" %>
                    <%= link_to "Edit", edit_admin_post_path(post.document_id), class: "btn btn-default" %>
                    <%= link_to "Delete", admin_post_path(post.document_id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
  </div>
</div>
<!-- /#page-wrapper -->

app/views/admin/posts/new.html.erb
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">新增</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Basic Form Elements
                </div>
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->