config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admin do
    resources :posts
  end

  
  get 'admin', to: 'admin#index'

  post '/tinymce_assets' => 'tinymce_assets#create'
  get 'index', to: 'page#index'
  root 'page#index'
  
  #get '*path', to: 'page#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'partials/navbar' if is_admin_path(controller_path()) %>
    <%= yield %>
    <%= javascript_include_tag 'admin_theme', 'data-turbolinks-track': 'reload' %>
    <% if ::Rails.application.assets.find_asset("#{controller_path()}.js") %>
      <%= javascript_include_tag controller_path() %>
    <% else %>
      <%= javascript_include_tag "admin/index" if is_admin_path(controller_path()) %>
    <% end %>
    <%= javascript_include_tag 'admin/vendor/sb-admin-2', 'data-turbolinks-track': 'reload' %>
    <%= yield(:script) %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CooReactRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>